from bs4 import BeautifulSoup

prompts=[
    "Black ink flows from the slender pen.", 
    "Ink-filled tool for writing or drawing purposes.", 
    "A writing utensil, essential for composing words.", 
    "A tool for writing, drawing and scribbling penmanship.", 
    "Brew, sip, relax, flavourful tea delight, enjoy.",
    "Brewed leaves, comforting sip, warming taste, tea.",
    "Soothing, warm, aromatic, flavorful, comforting, tea time.",
    "Steaming cup of joy, comforting Tea delight.",
    "Boat: Nautical vessel gliding on aquatic terrain.",
    "A boat on the sea, gracefully gliding.",
    "Floating vessel on water known as boat.",
    "Afloat away, boat riding on the waves.",
    "Beautiful wings flutter, it's a butterfly.",
    "Fluttering wings, a beautiful sight, a butterfly.",
    "Colorful wings flutter, a graceful butterfly.",
    "Beautiful wings flutter, it's a butterfly.",
    "Rustling leaves dance in the whimsical wind.",
    "A gust of air, blowing wind wild.",
    "Whistling wind whips waves with wild wails.",
    "Screaming and howling, nature's strong wind.",
    "Buzzing insect, yellow and black stripes, honey-maker.",
    "A honey-making insect with wings and stinger.",
    "A stripey insect that buzzes to the hive.",
    "A buzzing small creature that produces sweet honey.",
    "Loyal companion, barks and wags, man's best dog.",
    "Barking canine with a tail and paws - dog.",
    "Furry creature, always happy: man's faithful dog.",
    "Four-legged friend, barking sounds, lovable doggy.",
    "A playful primate with a tail - monkey.",
    "Mischievous primate swinging in trees, a monkey.",
    "Mischievous monkey eats bananas and swings on trees.",
    "Mischievous primate with a love for bananas.",
    "Sleek and fierce, the tiger roars loudly.",
    "Striking tiger stripes, powerful roar, fierce predator.",
    "Striking stripes on a powerful predator: Tiger",
    "Roaring, sprinting, striped, wild, feline, carnivorous, majestic, Tiger.",
    "Flower, delicate, fragrant, colorful, nature's beauty.",
    "Beautiful petals, fragrant aroma, epitomizes nature's flower.",
    "A pretty flower, blooming in the garden.",
    "Beautiful blossom flaunting its glory as flower.",
    "Flames raging high, a fire to quell.",
    "Flames leaping high, inferno burns in sight.",
    "Wild flames swallowing everything in their path.",
    "Dangerous flames spew from the burning fire.",
    "A clucking creature, fluffy and feathered - chicken.",
    "Small, feathery, clucking bird, that's a chicken.",
    "Fluffy feathers, sharp beak, clucking little chicken.",
    "Clucking bird, lays eggs, commonly known as chicken.",
    "Graceful creature with antlers on its head.",
    "Adeer is a majestic mammal resembling deer.",
    "Adeer is a quick and graceful runner.",
    "A deer-like creature with antlers and grace.",
    "Four-legged mammal with a mane, a horse.",
    "Equine mammal with hooves, known as horse.",
    "Four-legged animal, neighs and gallops - horse.",
    "Majestic, powerful, four-legged, galloping creature: horse.",
    "A flying creature with feathers; it's a bird.",
    "A chirping, feathered creature - it's a bird!",
    "An avian creature gracefully soaring high: bird.",
    "A chirping bird flying high in the sky.",
    "Majestic animal, a symbol of determination, an ox.",
    "Mighty warrior, strong as an ox.",
    "An ox-like bot, AOX helps with tasks.",
    "Anxious oxen avoid xylophones on weekends.",
    "A solid mineral object that lasts, stone.",
    "Hard, durable, mineral, rock-like, sedimentary stone.",
    "Hard, solid, natural, earthly, mineral, rock, durable, ancient.",
    "A solid, heavy, unyielding block of stone.",
    "A Book's pages hold worlds of wonder.",
    "The Book Thief stole my heart completely.",
    "A book is a binder of bound pages.",
    "The Book Thief stole my heart completely.",
    "Amazing agility and dexterity, a mouse majestically maneuvers.",
    "A mouse is a small rodent.",
    "A whiskered creature, scurrying like a mouse.",
    "A mouse scurrying through the house, quite stealthy.",
    "Towering, woody, rooted, branches, leaves, Arbor, perennial, canopy.",
    "Sturdy bark, rustling leaves, home for creatures.",
    "Branches, leaves, roots, trunk, shade — it's a tree.",
    "Tall, green, heartwood, branches, leaves, shade, home, oxygen.",
    "Big and furry, a grizzly bear roar.",
    "Brown fur, sharp claws, a fierce grizzly bear.",
    "A large, furry, mammal; that's a bear.",
    "Big furry mammal with sharp claws - Bear.",
    "A white blanket of glittering snowflakes falls.",
    "Whirling, white flakes blanket earth in snow.",
    "Fluffy white flakes fall softly from sky. (6 words with 'snow')",
    "Soft, white flakes fall gently, blanketing all below.",
    "Feathered, web-footed, quacking waterbird with webbed feet.",
    "Feathered fowl with webbed feet - a duck!",
    "A bird with feathers and webbed feet. ('Duck' is already included in the description.)",
    "A duck is a bird with webbed feet.",
    "Woolly, fluffy, grazing, bleating, farm, domesticated, mammal, sheep.",
    "Woolly, bleating, grazing, fluffy, domestic, herd animal.",
    "A fluffy, woolly, domesticated mammal known as sheep.",
    "Fleecy, docile, woolly, mammal, herbivore, ovine, bleat, sheep.",
    "Soaring high with powerful wings, an eagle.",
    "A bird with sharp eyes and strong wings.",
    "Aeagle soars high, eagle eyes see far.",
    "A majestic bird soaring high with keen eagle-eyed vision."
  ]

h=open('index.html','rb').read()
# print(h)
soup=BeautifulSoup(h)
divs = soup.find_all("div", class_="text-detail") # divs is a list of div elements
print(len(divs))
for i in range(100):
    p = divs[i].find("p") # get the first <p> element inside the div
    p.string = prompts[i] # change the text content to "123"

open('newindex.html','w').write(soup.prettify())
